version: '3'

services:
  web:
    build:
      context: ../../
      dockerfile: ./docker/dev/web/Dockerfile
    image: taskill_web_dev
    container_name: taskill_web_dev
    env_file: ./.env
    command: npm run serve
    ports:
      - ${VUE_APP_PORT}:${VUE_APP_PORT}
    volumes:
      - ../../client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - taskill-dev
    links:
      - api
  api:
    build:
      context: ../../
      dockerfile: ./docker/dev/api/Dockerfile
    image: taskill_api_dev
    container_name: taskill_api_dev
    env_file: ./.env
    command: >
      sh -c "../bin/wait-for-it.sh mongo:27017 -- echo "===\ mongo\ is\ up\ ===" && nodemon app.js"
    ports:
      - '${API_PORT}:${API_PORT}'
    restart: always
    volumes:
      - ../../server/:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - taskill-dev
    links:
      - mongo
  mongo:
    container_name: taskill_db_dev
    image: mongo
    volumes:
      - ../../data:/data/db
    networks:
      - taskill-dev
    ports:
      - '27100:27017'

networks:
  taskill-dev:
